# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f14519b3d00be98a230dc688b3a849d431374efd217a9cebe8195a537368806c13cadf4b620d97112184814ed29743be5bb01b9c52f4e1b1400142efe3892c9a

test:
  secret_key_base: e4baf8465f68114afba711beb6b62716cde1f369dd8ce9c02a7ec9e7f3b3f4b7d40ef3f347d4c038cd46c02a69f0f981bf959e58a9f7592996defd27692c7367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
